### ISSUE TITLE
App Crashed when change code in config.json

### ISSUE THREAD

**Issue by PabloMongayOlacia** [Michaelvilleneuve/lg-netcast-control#1]
Hi,
When I try to change the pairing code in config.json the app crashed on restart. 
I need to do something else? Any idea on what’s happening? 
Thanks.

**Comment by Michaelvilleneuve** [comment]
Hi, can you provide the error ? Are you sure the JSON is still valid ?

**Comment by PabloMongayOlacia** [comment]
That is what it says:

[nodemon] 1.17.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./node_modules/babel-cli/bin/babel-node.js app.js --presets node6`
module.js:674
    throw err;
    ^

SyntaxError: /home/pablo/lg-netcast-control/config.json: Unexpected number in JSON at position 13
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pablo/lg-netcast-control/LgApi.js:5:1)
    at Module._compile (module.js:652:30)
    at loader (/home/pablo/lg-netcast-control/node_modules/babel-register/lib/node.js:144:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Michaelvilleneuve** [comment]
Your JSON config file is invalid, paste it here if you want or try to fix it.

**Comment by PabloMongayOlacia** [comment]
Of course!

{
  "code": 052129,
  "ip": "192.168.43.120"
}

**Comment by Michaelvilleneuve** [comment]
Oh ok, that's because 052129 is not a a number because of the 0. Try passing it as a string.

**Comment by PabloMongayOlacia** [comment]
I was waiting to test it with the TVs...
Just changing JSON like: 
{
"code": “052129”,
"ip": "192.168.43.120"
}
And it works perfect.
Lots of thanks!

**Comment by Michaelvilleneuve** [comment]
You're welcome !
